select * from customer limit 20
--q1 what is total revenue generated by men and male vs female
select gender ,sum(purchase_amount)as revenue
from customer
group by gender
SELECT customer_id, purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer
)
select item_purchased ,ROUND(AVG(review_rating:: numeric),2) as "Average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;
select item_purchased,
SU